---
- hosts: "{{ worker }}:!{{ master }}"
  gather_facts: false
  remote_user: student
  vars:
    - deployment_path: "/home/student/DERAM"
    - jar: "DERAM-1.0.jar"
  tasks:
  - name: run worker for experiment {{ experiment_nr }}
    command:
      argv:
        - "./experiment.sh"
        - "{{ experiment_nr }}"
        - "{{ jar }}"
        - "worker"
        - "{{ master }}"
    async: 10000
    poll: 0
    args:
      chdir: "{{ deployment_path }}"

- hosts: '{{ master }}'
  gather_facts: false
  remote_user: student
  vars:
    - deployment_path: "/home/student/DERAM"
    - jar: "DERAM-1.0.jar"
  tasks:
  - name: run master for experiment {{ experiment_nr }}
    command:
      argv:
        - "./experiment.sh"
        - "{{ experiment_nr }}"
        - "{{ jar }}"
        - "master"
        - "{{ master }}"
    args:
      chdir: "{{ deployment_path }}"

- hosts: 127.0.0.1
  gather_facts: false
  connection: local
  tasks:
  - name: ensure local result directory exists
    file:
      path: "{{ result_dir }}"
      state: directory

- hosts: "{{ worker }}:{{ master }}"
  gather_facts: false
  remote_user: student
  vars:
    - deployment_path: "/home/student/DERAM"
  tasks:

  - name: get results from experiment {{ experiment_nr }}
    synchronize:  
      src: "{{ deployment_path }}/experiment_{{ experiment_nr }}/result/"
      dest: "{{ result_dir }}"
      mode: pull
